name: Auto-Format and PR
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - "**.lock"
      - "home/**"

concurrency:
  group: format-and-pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  format-and-pr:
    name: Format and PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          persist-credentials: false
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v15

      - name: Format files
        run: |
          nix fmt
          nix run .#treefmt

      - name: Check for changes
        id: check_changes
        shell: bash
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "NO_CHANGES=1" >> "$GITHUB_ENV"
          else
            echo "NO_CHANGES=0" >> "$GITHUB_ENV"
          fi

      - name: Commit and push changes
        if: env.NO_CHANGES != '1'
        shell: bash
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit -m "chore: auto-format files"
          git push

      - name: Open PR
        if: env.NO_CHANGES != '1'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: auto-format files"
          title: "chore: auto-format files"
          body: "Automated formatting changes."
          branch: "auto-format-branch"
          base: ${{ github.ref_name }}
          delete-branch: true
