name: "Update submodules"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "51 2 * * *"

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          git submodule update --init --recursive --remote
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update submodules" || exit 0

      - id: pr
        uses: peter-evans/create-pull-request@v8
        with:
          title: Update SubModules
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.pr.outputs.pull-request-number
        run: gh pr merge ${{ steps.pr.outputs.pull-request-number }} --squash --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
